/* tslint:disable */
/* eslint-disable */
/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TradeSymbol } from './TradeSymbol';
import {
    TradeSymbolFromJSON,
    TradeSymbolFromJSONTyped,
    TradeSymbolToJSON,
} from './TradeSymbol';

/**
 * The details of the required construction materials for a given waypoint under construction.
 * @export
 * @interface ConstructionMaterial
 */
export interface ConstructionMaterial {
    /**
     * 
     * @type {TradeSymbol}
     * @memberof ConstructionMaterial
     */
    tradeSymbol: TradeSymbol;
    /**
     * The number of units required.
     * @type {number}
     * @memberof ConstructionMaterial
     */
    required: number;
    /**
     * The number of units fulfilled toward the required amount.
     * @type {number}
     * @memberof ConstructionMaterial
     */
    fulfilled: number;
}

/**
 * Check if a given object implements the ConstructionMaterial interface.
 */
export function instanceOfConstructionMaterial(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "tradeSymbol" in value;
    isInstance = isInstance && "required" in value;
    isInstance = isInstance && "fulfilled" in value;

    return isInstance;
}

export function ConstructionMaterialFromJSON(json: any): ConstructionMaterial {
    return ConstructionMaterialFromJSONTyped(json, false);
}

export function ConstructionMaterialFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConstructionMaterial {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tradeSymbol': TradeSymbolFromJSON(json['tradeSymbol']),
        'required': json['required'],
        'fulfilled': json['fulfilled'],
    };
}

export function ConstructionMaterialToJSON(value?: ConstructionMaterial | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tradeSymbol': TradeSymbolToJSON(value.tradeSymbol),
        'required': value.required,
        'fulfilled': value.fulfilled,
    };
}

