/* tslint:disable */
/* eslint-disable */
/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Chart } from './Chart';
import {
    ChartFromJSON,
    ChartFromJSONTyped,
    ChartToJSON,
} from './Chart';
import type { Waypoint } from './Waypoint';
import {
    WaypointFromJSON,
    WaypointFromJSONTyped,
    WaypointToJSON,
} from './Waypoint';

/**
 * 
 * @export
 * @interface CreateChart201ResponseData
 */
export interface CreateChart201ResponseData {
    /**
     * 
     * @type {Chart}
     * @memberof CreateChart201ResponseData
     */
    chart: Chart;
    /**
     * 
     * @type {Waypoint}
     * @memberof CreateChart201ResponseData
     */
    waypoint: Waypoint;
}

/**
 * Check if a given object implements the CreateChart201ResponseData interface.
 */
export function instanceOfCreateChart201ResponseData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "chart" in value;
    isInstance = isInstance && "waypoint" in value;

    return isInstance;
}

export function CreateChart201ResponseDataFromJSON(json: any): CreateChart201ResponseData {
    return CreateChart201ResponseDataFromJSONTyped(json, false);
}

export function CreateChart201ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateChart201ResponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'chart': ChartFromJSON(json['chart']),
        'waypoint': WaypointFromJSON(json['waypoint']),
    };
}

export function CreateChart201ResponseDataToJSON(value?: CreateChart201ResponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'chart': ChartToJSON(value.chart),
        'waypoint': WaypointToJSON(value.waypoint),
    };
}

