/* tslint:disable */
/* eslint-disable */
/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { GetWaypoint200ResponseDataChart } from './get-waypoint200-response-data-chart';
// May contain unused imports in some cases
// @ts-ignore
import { GetWaypoint200ResponseDataFaction } from './get-waypoint200-response-data-faction';

/**
 * A waypoint is a location that ships can travel to such as a Planet, Moon or Space Station.
 * @export
 * @interface GetWaypoint200ResponseData
 */
export interface GetWaypoint200ResponseData {
    /**
     * The symbol of the waypoint.
     * @type {any}
     * @memberof GetWaypoint200ResponseData
     */
    'symbol': any;
    /**
     * The type of waypoint.
     * @type {any}
     * @memberof GetWaypoint200ResponseData
     */
    'type': GetWaypoint200ResponseDataTypeEnum;
    /**
     * The symbol of the system.
     * @type {any}
     * @memberof GetWaypoint200ResponseData
     */
    'systemSymbol': any;
    /**
     * Relative position of the waypoint on the system\'s x axis. This is not an absolute position in the universe.
     * @type {any}
     * @memberof GetWaypoint200ResponseData
     */
    'x': any;
    /**
     * Relative position of the waypoint on the system\'s y axis. This is not an absolute position in the universe.
     * @type {any}
     * @memberof GetWaypoint200ResponseData
     */
    'y': any;
    /**
     * Waypoints that orbit this waypoint.
     * @type {any}
     * @memberof GetWaypoint200ResponseData
     */
    'orbitals': any;
    /**
     * The symbol of the parent waypoint, if this waypoint is in orbit around another waypoint. Otherwise this value is undefined.
     * @type {any}
     * @memberof GetWaypoint200ResponseData
     */
    'orbits'?: any;
    /**
     * 
     * @type {GetWaypoint200ResponseDataFaction}
     * @memberof GetWaypoint200ResponseData
     */
    'faction'?: GetWaypoint200ResponseDataFaction;
    /**
     * The traits of the waypoint.
     * @type {any}
     * @memberof GetWaypoint200ResponseData
     */
    'traits': any;
    /**
     * The modifiers of the waypoint.
     * @type {any}
     * @memberof GetWaypoint200ResponseData
     */
    'modifiers'?: any;
    /**
     * 
     * @type {GetWaypoint200ResponseDataChart}
     * @memberof GetWaypoint200ResponseData
     */
    'chart'?: GetWaypoint200ResponseDataChart;
    /**
     * True if the waypoint is under construction.
     * @type {any}
     * @memberof GetWaypoint200ResponseData
     */
    'isUnderConstruction': any;
}

export const GetWaypoint200ResponseDataTypeEnum = {
    Planet: 'PLANET',
    GasGiant: 'GAS_GIANT',
    Moon: 'MOON',
    OrbitalStation: 'ORBITAL_STATION',
    JumpGate: 'JUMP_GATE',
    AsteroidField: 'ASTEROID_FIELD',
    Asteroid: 'ASTEROID',
    EngineeredAsteroid: 'ENGINEERED_ASTEROID',
    AsteroidBase: 'ASTEROID_BASE',
    Nebula: 'NEBULA',
    DebrisField: 'DEBRIS_FIELD',
    GravityWell: 'GRAVITY_WELL',
    ArtificialGravityWell: 'ARTIFICIAL_GRAVITY_WELL',
    FuelStation: 'FUEL_STATION'
} as const;

export type GetWaypoint200ResponseDataTypeEnum = typeof GetWaypoint200ResponseDataTypeEnum[keyof typeof GetWaypoint200ResponseDataTypeEnum];


