/* tslint:disable */
/* eslint-disable */
/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetMarket200ResponseData
 */
export interface GetMarket200ResponseData {
    /**
     * The symbol of the market. The symbol is the same as the waypoint where the market is located.
     * @type {any}
     * @memberof GetMarket200ResponseData
     */
    symbol: any | null;
    /**
     * The list of goods that are exported from this market.
     * @type {any}
     * @memberof GetMarket200ResponseData
     */
    exports: any | null;
    /**
     * The list of goods that are sought as imports in this market.
     * @type {any}
     * @memberof GetMarket200ResponseData
     */
    imports: any | null;
    /**
     * The list of goods that are bought and sold between agents at this market.
     * @type {any}
     * @memberof GetMarket200ResponseData
     */
    exchange: any | null;
    /**
     * The list of recent transactions at this market. Visible only when a ship is present at the market.
     * @type {any}
     * @memberof GetMarket200ResponseData
     */
    transactions?: any | null;
    /**
     * The list of goods that are traded at this market. Visible only when a ship is present at the market.
     * @type {any}
     * @memberof GetMarket200ResponseData
     */
    tradeGoods?: any | null;
}

/**
 * Check if a given object implements the GetMarket200ResponseData interface.
 */
export function instanceOfGetMarket200ResponseData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "symbol" in value;
    isInstance = isInstance && "exports" in value;
    isInstance = isInstance && "imports" in value;
    isInstance = isInstance && "exchange" in value;

    return isInstance;
}

export function GetMarket200ResponseDataFromJSON(json: any): GetMarket200ResponseData {
    return GetMarket200ResponseDataFromJSONTyped(json, false);
}

export function GetMarket200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMarket200ResponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'symbol': json['symbol'],
        'exports': json['exports'],
        'imports': json['imports'],
        'exchange': json['exchange'],
        'transactions': !exists(json, 'transactions') ? undefined : json['transactions'],
        'tradeGoods': !exists(json, 'tradeGoods') ? undefined : json['tradeGoods'],
    };
}

export function GetMarket200ResponseDataToJSON(value?: GetMarket200ResponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'symbol': value.symbol,
        'exports': value.exports,
        'imports': value.imports,
        'exchange': value.exchange,
        'transactions': value.transactions,
        'tradeGoods': value.tradeGoods,
    };
}

