/* tslint:disable */
/* eslint-disable */
/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetStatus200ResponseLeaderboardsMostSubmittedChartsInner
 */
export interface GetStatus200ResponseLeaderboardsMostSubmittedChartsInner {
    /**
     * Symbol of the agent.
     * @type {string}
     * @memberof GetStatus200ResponseLeaderboardsMostSubmittedChartsInner
     */
    agentSymbol: string;
    /**
     * Amount of charts done by the agent.
     * @type {number}
     * @memberof GetStatus200ResponseLeaderboardsMostSubmittedChartsInner
     */
    chartCount: number;
}

/**
 * Check if a given object implements the GetStatus200ResponseLeaderboardsMostSubmittedChartsInner interface.
 */
export function instanceOfGetStatus200ResponseLeaderboardsMostSubmittedChartsInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "agentSymbol" in value;
    isInstance = isInstance && "chartCount" in value;

    return isInstance;
}

export function GetStatus200ResponseLeaderboardsMostSubmittedChartsInnerFromJSON(json: any): GetStatus200ResponseLeaderboardsMostSubmittedChartsInner {
    return GetStatus200ResponseLeaderboardsMostSubmittedChartsInnerFromJSONTyped(json, false);
}

export function GetStatus200ResponseLeaderboardsMostSubmittedChartsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetStatus200ResponseLeaderboardsMostSubmittedChartsInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'agentSymbol': json['agentSymbol'],
        'chartCount': json['chartCount'],
    };
}

export function GetStatus200ResponseLeaderboardsMostSubmittedChartsInnerToJSON(value?: GetStatus200ResponseLeaderboardsMostSubmittedChartsInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'agentSymbol': value.agentSymbol,
        'chartCount': value.chartCount,
    };
}

