/* tslint:disable */
/* eslint-disable */
/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InstallMount201ResponseDataTransaction
 */
export interface InstallMount201ResponseDataTransaction {
    /**
     * The total price of the transaction.
     * @type {number}
     * @memberof InstallMount201ResponseDataTransaction
     */
    totalPrice: number;
    /**
     * The timestamp of the transaction.
     * @type {string}
     * @memberof InstallMount201ResponseDataTransaction
     */
    timestamp: string;
}

/**
 * Check if a given object implements the InstallMount201ResponseDataTransaction interface.
 */
export function instanceOfInstallMount201ResponseDataTransaction(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "totalPrice" in value;
    isInstance = isInstance && "timestamp" in value;

    return isInstance;
}

export function InstallMount201ResponseDataTransactionFromJSON(json: any): InstallMount201ResponseDataTransaction {
    return InstallMount201ResponseDataTransactionFromJSONTyped(json, false);
}

export function InstallMount201ResponseDataTransactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstallMount201ResponseDataTransaction {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'totalPrice': json['totalPrice'],
        'timestamp': json['timestamp'],
    };
}

export function InstallMount201ResponseDataTransactionToJSON(value?: InstallMount201ResponseDataTransaction | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'totalPrice': value.totalPrice,
        'timestamp': value.timestamp,
    };
}

