/* tslint:disable */
/* eslint-disable */
/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Result of a transaction with a market.
 * @export
 * @interface JumpShip200ResponseDataTransaction
 */
export interface JumpShip200ResponseDataTransaction {
    /**
     * The symbol of the waypoint.
     * @type {any}
     * @memberof JumpShip200ResponseDataTransaction
     */
    waypointSymbol: any | null;
    /**
     * The symbol of the ship that made the transaction.
     * @type {any}
     * @memberof JumpShip200ResponseDataTransaction
     */
    shipSymbol: any | null;
    /**
     * The symbol of the trade good.
     * @type {any}
     * @memberof JumpShip200ResponseDataTransaction
     */
    tradeSymbol: any | null;
    /**
     * The type of transaction.
     * @type {any}
     * @memberof JumpShip200ResponseDataTransaction
     */
    type: JumpShip200ResponseDataTransactionTypeEnum;
    /**
     * The number of units of the transaction.
     * @type {any}
     * @memberof JumpShip200ResponseDataTransaction
     */
    units: any | null;
    /**
     * The price per unit of the transaction.
     * @type {any}
     * @memberof JumpShip200ResponseDataTransaction
     */
    pricePerUnit: any | null;
    /**
     * The total price of the transaction.
     * @type {any}
     * @memberof JumpShip200ResponseDataTransaction
     */
    totalPrice: any | null;
    /**
     * The timestamp of the transaction.
     * @type {any}
     * @memberof JumpShip200ResponseDataTransaction
     */
    timestamp: any | null;
}


/**
 * @export
 */
export const JumpShip200ResponseDataTransactionTypeEnum = {
    Purchase: 'PURCHASE',
    Sell: 'SELL'
} as const;
export type JumpShip200ResponseDataTransactionTypeEnum = typeof JumpShip200ResponseDataTransactionTypeEnum[keyof typeof JumpShip200ResponseDataTransactionTypeEnum];


/**
 * Check if a given object implements the JumpShip200ResponseDataTransaction interface.
 */
export function instanceOfJumpShip200ResponseDataTransaction(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "waypointSymbol" in value;
    isInstance = isInstance && "shipSymbol" in value;
    isInstance = isInstance && "tradeSymbol" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "units" in value;
    isInstance = isInstance && "pricePerUnit" in value;
    isInstance = isInstance && "totalPrice" in value;
    isInstance = isInstance && "timestamp" in value;

    return isInstance;
}

export function JumpShip200ResponseDataTransactionFromJSON(json: any): JumpShip200ResponseDataTransaction {
    return JumpShip200ResponseDataTransactionFromJSONTyped(json, false);
}

export function JumpShip200ResponseDataTransactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): JumpShip200ResponseDataTransaction {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'waypointSymbol': json['waypointSymbol'],
        'shipSymbol': json['shipSymbol'],
        'tradeSymbol': json['tradeSymbol'],
        'type': json['type'],
        'units': json['units'],
        'pricePerUnit': json['pricePerUnit'],
        'totalPrice': json['totalPrice'],
        'timestamp': json['timestamp'],
    };
}

export function JumpShip200ResponseDataTransactionToJSON(value?: JumpShip200ResponseDataTransaction | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'waypointSymbol': value.waypointSymbol,
        'shipSymbol': value.shipSymbol,
        'tradeSymbol': value.tradeSymbol,
        'type': value.type,
        'units': value.units,
        'pricePerUnit': value.pricePerUnit,
        'totalPrice': value.totalPrice,
        'timestamp': value.timestamp,
    };
}

