/* tslint:disable */
/* eslint-disable */
/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Register201ResponseDataShipNav } from './Register201ResponseDataShipNav';
import {
    Register201ResponseDataShipNavFromJSON,
    Register201ResponseDataShipNavFromJSONTyped,
    Register201ResponseDataShipNavToJSON,
} from './Register201ResponseDataShipNav';

/**
 * 
 * @export
 * @interface OrbitShip200ResponseData
 */
export interface OrbitShip200ResponseData {
    /**
     * 
     * @type {Register201ResponseDataShipNav}
     * @memberof OrbitShip200ResponseData
     */
    nav: Register201ResponseDataShipNav;
}

/**
 * Check if a given object implements the OrbitShip200ResponseData interface.
 */
export function instanceOfOrbitShip200ResponseData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "nav" in value;

    return isInstance;
}

export function OrbitShip200ResponseDataFromJSON(json: any): OrbitShip200ResponseData {
    return OrbitShip200ResponseDataFromJSONTyped(json, false);
}

export function OrbitShip200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrbitShip200ResponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nav': Register201ResponseDataShipNavFromJSON(json['nav']),
    };
}

export function OrbitShip200ResponseDataToJSON(value?: OrbitShip200ResponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'nav': Register201ResponseDataShipNavToJSON(value.nav),
    };
}

