/* tslint:disable */
/* eslint-disable */
/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Register201ResponseDataShipNavRouteDestination } from './Register201ResponseDataShipNavRouteDestination';
import {
    Register201ResponseDataShipNavRouteDestinationFromJSON,
    Register201ResponseDataShipNavRouteDestinationFromJSONTyped,
    Register201ResponseDataShipNavRouteDestinationToJSON,
} from './Register201ResponseDataShipNavRouteDestination';

/**
 * The routing information for the ship's most recent transit or current location.
 * @export
 * @interface Register201ResponseDataShipNavRoute
 */
export interface Register201ResponseDataShipNavRoute {
    /**
     * 
     * @type {Register201ResponseDataShipNavRouteDestination}
     * @memberof Register201ResponseDataShipNavRoute
     */
    destination: Register201ResponseDataShipNavRouteDestination;
    /**
     * 
     * @type {Register201ResponseDataShipNavRouteDestination}
     * @memberof Register201ResponseDataShipNavRoute
     */
    origin: Register201ResponseDataShipNavRouteDestination;
    /**
     * The date time of the ship's departure.
     * @type {any}
     * @memberof Register201ResponseDataShipNavRoute
     */
    departureTime: any | null;
    /**
     * The date time of the ship's arrival. If the ship is in-transit, this is the expected time of arrival.
     * @type {any}
     * @memberof Register201ResponseDataShipNavRoute
     */
    arrival: any | null;
}

/**
 * Check if a given object implements the Register201ResponseDataShipNavRoute interface.
 */
export function instanceOfRegister201ResponseDataShipNavRoute(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "destination" in value;
    isInstance = isInstance && "origin" in value;
    isInstance = isInstance && "departureTime" in value;
    isInstance = isInstance && "arrival" in value;

    return isInstance;
}

export function Register201ResponseDataShipNavRouteFromJSON(json: any): Register201ResponseDataShipNavRoute {
    return Register201ResponseDataShipNavRouteFromJSONTyped(json, false);
}

export function Register201ResponseDataShipNavRouteFromJSONTyped(json: any, ignoreDiscriminator: boolean): Register201ResponseDataShipNavRoute {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'destination': Register201ResponseDataShipNavRouteDestinationFromJSON(json['destination']),
        'origin': Register201ResponseDataShipNavRouteDestinationFromJSON(json['origin']),
        'departureTime': json['departureTime'],
        'arrival': json['arrival'],
    };
}

export function Register201ResponseDataShipNavRouteToJSON(value?: Register201ResponseDataShipNavRoute | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'destination': Register201ResponseDataShipNavRouteDestinationToJSON(value.destination),
        'origin': Register201ResponseDataShipNavRouteDestinationToJSON(value.origin),
        'departureTime': value.departureTime,
        'arrival': value.arrival,
    };
}

