/* tslint:disable */
/* eslint-disable */
/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Register201ResponseDataShipCargo } from './register201-response-data-ship-cargo';
// May contain unused imports in some cases
// @ts-ignore
import { Register201ResponseDataShipCooldown } from './register201-response-data-ship-cooldown';
// May contain unused imports in some cases
// @ts-ignore
import { Register201ResponseDataShipCrew } from './register201-response-data-ship-crew';
// May contain unused imports in some cases
// @ts-ignore
import { Register201ResponseDataShipEngine } from './register201-response-data-ship-engine';
// May contain unused imports in some cases
// @ts-ignore
import { Register201ResponseDataShipFrame } from './register201-response-data-ship-frame';
// May contain unused imports in some cases
// @ts-ignore
import { Register201ResponseDataShipFuel } from './register201-response-data-ship-fuel';
// May contain unused imports in some cases
// @ts-ignore
import { Register201ResponseDataShipNav } from './register201-response-data-ship-nav';
// May contain unused imports in some cases
// @ts-ignore
import { Register201ResponseDataShipReactor } from './register201-response-data-ship-reactor';
// May contain unused imports in some cases
// @ts-ignore
import { Register201ResponseDataShipRegistration } from './register201-response-data-ship-registration';

/**
 * Ship details.
 * @export
 * @interface Register201ResponseDataShip
 */
export interface Register201ResponseDataShip {
    /**
     * The globally unique identifier of the ship in the following format: `[AGENT_SYMBOL]-[HEX_ID]`
     * @type {any}
     * @memberof Register201ResponseDataShip
     */
    'symbol': any;
    /**
     * 
     * @type {Register201ResponseDataShipRegistration}
     * @memberof Register201ResponseDataShip
     */
    'registration': Register201ResponseDataShipRegistration;
    /**
     * 
     * @type {Register201ResponseDataShipNav}
     * @memberof Register201ResponseDataShip
     */
    'nav': Register201ResponseDataShipNav;
    /**
     * 
     * @type {Register201ResponseDataShipCrew}
     * @memberof Register201ResponseDataShip
     */
    'crew': Register201ResponseDataShipCrew;
    /**
     * 
     * @type {Register201ResponseDataShipFrame}
     * @memberof Register201ResponseDataShip
     */
    'frame': Register201ResponseDataShipFrame;
    /**
     * 
     * @type {Register201ResponseDataShipReactor}
     * @memberof Register201ResponseDataShip
     */
    'reactor': Register201ResponseDataShipReactor;
    /**
     * 
     * @type {Register201ResponseDataShipEngine}
     * @memberof Register201ResponseDataShip
     */
    'engine': Register201ResponseDataShipEngine;
    /**
     * 
     * @type {Register201ResponseDataShipCooldown}
     * @memberof Register201ResponseDataShip
     */
    'cooldown': Register201ResponseDataShipCooldown;
    /**
     * Modules installed in this ship.
     * @type {any}
     * @memberof Register201ResponseDataShip
     */
    'modules': any;
    /**
     * Mounts installed in this ship.
     * @type {any}
     * @memberof Register201ResponseDataShip
     */
    'mounts': any;
    /**
     * 
     * @type {Register201ResponseDataShipCargo}
     * @memberof Register201ResponseDataShip
     */
    'cargo': Register201ResponseDataShipCargo;
    /**
     * 
     * @type {Register201ResponseDataShipFuel}
     * @memberof Register201ResponseDataShip
     */
    'fuel': Register201ResponseDataShipFuel;
}

