/* tslint:disable */
/* eslint-disable */
/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Register201ResponseDataContractTerms } from './Register201ResponseDataContractTerms';
import {
    Register201ResponseDataContractTermsFromJSON,
    Register201ResponseDataContractTermsFromJSONTyped,
    Register201ResponseDataContractTermsToJSON,
} from './Register201ResponseDataContractTerms';

/**
 * Contract details.
 * @export
 * @interface Register201ResponseDataContract
 */
export interface Register201ResponseDataContract {
    /**
     * ID of the contract.
     * @type {any}
     * @memberof Register201ResponseDataContract
     */
    id: any | null;
    /**
     * The symbol of the faction that this contract is for.
     * @type {any}
     * @memberof Register201ResponseDataContract
     */
    factionSymbol: any | null;
    /**
     * Type of contract.
     * @type {any}
     * @memberof Register201ResponseDataContract
     */
    type: Register201ResponseDataContractTypeEnum;
    /**
     * 
     * @type {Register201ResponseDataContractTerms}
     * @memberof Register201ResponseDataContract
     */
    terms: Register201ResponseDataContractTerms;
    /**
     * Whether the contract has been accepted by the agent
     * @type {any}
     * @memberof Register201ResponseDataContract
     */
    accepted: any | null;
    /**
     * Whether the contract has been fulfilled
     * @type {any}
     * @memberof Register201ResponseDataContract
     */
    fulfilled: any | null;
    /**
     * Deprecated in favor of deadlineToAccept
     * @type {any}
     * @memberof Register201ResponseDataContract
     * @deprecated
     */
    expiration: any | null;
    /**
     * The time at which the contract is no longer available to be accepted
     * @type {any}
     * @memberof Register201ResponseDataContract
     */
    deadlineToAccept?: any | null;
}


/**
 * @export
 */
export const Register201ResponseDataContractTypeEnum = {
    Procurement: 'PROCUREMENT',
    Transport: 'TRANSPORT',
    Shuttle: 'SHUTTLE'
} as const;
export type Register201ResponseDataContractTypeEnum = typeof Register201ResponseDataContractTypeEnum[keyof typeof Register201ResponseDataContractTypeEnum];


/**
 * Check if a given object implements the Register201ResponseDataContract interface.
 */
export function instanceOfRegister201ResponseDataContract(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "factionSymbol" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "terms" in value;
    isInstance = isInstance && "accepted" in value;
    isInstance = isInstance && "fulfilled" in value;
    isInstance = isInstance && "expiration" in value;

    return isInstance;
}

export function Register201ResponseDataContractFromJSON(json: any): Register201ResponseDataContract {
    return Register201ResponseDataContractFromJSONTyped(json, false);
}

export function Register201ResponseDataContractFromJSONTyped(json: any, ignoreDiscriminator: boolean): Register201ResponseDataContract {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'factionSymbol': json['factionSymbol'],
        'type': json['type'],
        'terms': Register201ResponseDataContractTermsFromJSON(json['terms']),
        'accepted': json['accepted'],
        'fulfilled': json['fulfilled'],
        'expiration': json['expiration'],
        'deadlineToAccept': !exists(json, 'deadlineToAccept') ? undefined : json['deadlineToAccept'],
    };
}

export function Register201ResponseDataContractToJSON(value?: Register201ResponseDataContract | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'factionSymbol': value.factionSymbol,
        'type': value.type,
        'terms': Register201ResponseDataContractTermsToJSON(value.terms),
        'accepted': value.accepted,
        'fulfilled': value.fulfilled,
        'expiration': value.expiration,
        'deadlineToAccept': value.deadlineToAccept,
    };
}

