/* tslint:disable */
/* eslint-disable */
/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The destination or departure of a ships nav route.
 * @export
 * @interface Register201ResponseDataShipNavRouteDestination
 */
export interface Register201ResponseDataShipNavRouteDestination {
    /**
     * The symbol of the waypoint.
     * @type {any}
     * @memberof Register201ResponseDataShipNavRouteDestination
     */
    symbol: any | null;
    /**
     * The type of waypoint.
     * @type {any}
     * @memberof Register201ResponseDataShipNavRouteDestination
     */
    type: Register201ResponseDataShipNavRouteDestinationTypeEnum;
    /**
     * The symbol of the system.
     * @type {any}
     * @memberof Register201ResponseDataShipNavRouteDestination
     */
    systemSymbol: any | null;
    /**
     * Position in the universe in the x axis.
     * @type {any}
     * @memberof Register201ResponseDataShipNavRouteDestination
     */
    x: any | null;
    /**
     * Position in the universe in the y axis.
     * @type {any}
     * @memberof Register201ResponseDataShipNavRouteDestination
     */
    y: any | null;
}


/**
 * @export
 */
export const Register201ResponseDataShipNavRouteDestinationTypeEnum = {
    Planet: 'PLANET',
    GasGiant: 'GAS_GIANT',
    Moon: 'MOON',
    OrbitalStation: 'ORBITAL_STATION',
    JumpGate: 'JUMP_GATE',
    AsteroidField: 'ASTEROID_FIELD',
    Asteroid: 'ASTEROID',
    EngineeredAsteroid: 'ENGINEERED_ASTEROID',
    AsteroidBase: 'ASTEROID_BASE',
    Nebula: 'NEBULA',
    DebrisField: 'DEBRIS_FIELD',
    GravityWell: 'GRAVITY_WELL',
    ArtificialGravityWell: 'ARTIFICIAL_GRAVITY_WELL',
    FuelStation: 'FUEL_STATION'
} as const;
export type Register201ResponseDataShipNavRouteDestinationTypeEnum = typeof Register201ResponseDataShipNavRouteDestinationTypeEnum[keyof typeof Register201ResponseDataShipNavRouteDestinationTypeEnum];


/**
 * Check if a given object implements the Register201ResponseDataShipNavRouteDestination interface.
 */
export function instanceOfRegister201ResponseDataShipNavRouteDestination(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "symbol" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "systemSymbol" in value;
    isInstance = isInstance && "x" in value;
    isInstance = isInstance && "y" in value;

    return isInstance;
}

export function Register201ResponseDataShipNavRouteDestinationFromJSON(json: any): Register201ResponseDataShipNavRouteDestination {
    return Register201ResponseDataShipNavRouteDestinationFromJSONTyped(json, false);
}

export function Register201ResponseDataShipNavRouteDestinationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Register201ResponseDataShipNavRouteDestination {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'symbol': json['symbol'],
        'type': json['type'],
        'systemSymbol': json['systemSymbol'],
        'x': json['x'],
        'y': json['y'],
    };
}

export function Register201ResponseDataShipNavRouteDestinationToJSON(value?: Register201ResponseDataShipNavRouteDestination | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'symbol': value.symbol,
        'type': value.type,
        'systemSymbol': value.systemSymbol,
        'x': value.x,
        'y': value.y,
    };
}

