/* tslint:disable */
/* eslint-disable */
/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Register201ResponseDataContractTermsPayment } from './Register201ResponseDataContractTermsPayment';
import {
    Register201ResponseDataContractTermsPaymentFromJSON,
    Register201ResponseDataContractTermsPaymentFromJSONTyped,
    Register201ResponseDataContractTermsPaymentToJSON,
} from './Register201ResponseDataContractTermsPayment';

/**
 * The terms to fulfill the contract.
 * @export
 * @interface Register201ResponseDataContractTerms
 */
export interface Register201ResponseDataContractTerms {
    /**
     * The deadline for the contract.
     * @type {any}
     * @memberof Register201ResponseDataContractTerms
     */
    deadline: any | null;
    /**
     * 
     * @type {Register201ResponseDataContractTermsPayment}
     * @memberof Register201ResponseDataContractTerms
     */
    payment: Register201ResponseDataContractTermsPayment;
    /**
     * The cargo that needs to be delivered to fulfill the contract.
     * @type {any}
     * @memberof Register201ResponseDataContractTerms
     */
    deliver?: any | null;
}

/**
 * Check if a given object implements the Register201ResponseDataContractTerms interface.
 */
export function instanceOfRegister201ResponseDataContractTerms(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "deadline" in value;
    isInstance = isInstance && "payment" in value;

    return isInstance;
}

export function Register201ResponseDataContractTermsFromJSON(json: any): Register201ResponseDataContractTerms {
    return Register201ResponseDataContractTermsFromJSONTyped(json, false);
}

export function Register201ResponseDataContractTermsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Register201ResponseDataContractTerms {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'deadline': json['deadline'],
        'payment': Register201ResponseDataContractTermsPaymentFromJSON(json['payment']),
        'deliver': !exists(json, 'deliver') ? undefined : json['deliver'],
    };
}

export function Register201ResponseDataContractTermsToJSON(value?: Register201ResponseDataContractTerms | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'deadline': value.deadline,
        'payment': Register201ResponseDataContractTermsPaymentToJSON(value.payment),
        'deliver': value.deliver,
    };
}

