/* tslint:disable */
/* eslint-disable */
/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { JumpShip200ResponseDataTransaction } from './JumpShip200ResponseDataTransaction';
import {
    JumpShip200ResponseDataTransactionFromJSON,
    JumpShip200ResponseDataTransactionFromJSONTyped,
    JumpShip200ResponseDataTransactionToJSON,
} from './JumpShip200ResponseDataTransaction';
import type { Register201ResponseDataAgent } from './Register201ResponseDataAgent';
import {
    Register201ResponseDataAgentFromJSON,
    Register201ResponseDataAgentFromJSONTyped,
    Register201ResponseDataAgentToJSON,
} from './Register201ResponseDataAgent';
import type { Register201ResponseDataShipCargo } from './Register201ResponseDataShipCargo';
import {
    Register201ResponseDataShipCargoFromJSON,
    Register201ResponseDataShipCargoFromJSONTyped,
    Register201ResponseDataShipCargoToJSON,
} from './Register201ResponseDataShipCargo';

/**
 * 
 * @export
 * @interface SellCargo201ResponseData
 */
export interface SellCargo201ResponseData {
    /**
     * 
     * @type {Register201ResponseDataAgent}
     * @memberof SellCargo201ResponseData
     */
    agent: Register201ResponseDataAgent;
    /**
     * 
     * @type {Register201ResponseDataShipCargo}
     * @memberof SellCargo201ResponseData
     */
    cargo: Register201ResponseDataShipCargo;
    /**
     * 
     * @type {JumpShip200ResponseDataTransaction}
     * @memberof SellCargo201ResponseData
     */
    transaction: JumpShip200ResponseDataTransaction;
}

/**
 * Check if a given object implements the SellCargo201ResponseData interface.
 */
export function instanceOfSellCargo201ResponseData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "agent" in value;
    isInstance = isInstance && "cargo" in value;
    isInstance = isInstance && "transaction" in value;

    return isInstance;
}

export function SellCargo201ResponseDataFromJSON(json: any): SellCargo201ResponseData {
    return SellCargo201ResponseDataFromJSONTyped(json, false);
}

export function SellCargo201ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SellCargo201ResponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'agent': Register201ResponseDataAgentFromJSON(json['agent']),
        'cargo': Register201ResponseDataShipCargoFromJSON(json['cargo']),
        'transaction': JumpShip200ResponseDataTransactionFromJSON(json['transaction']),
    };
}

export function SellCargo201ResponseDataToJSON(value?: SellCargo201ResponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'agent': Register201ResponseDataAgentToJSON(value.agent),
        'cargo': Register201ResponseDataShipCargoToJSON(value.cargo),
        'transaction': JumpShip200ResponseDataTransactionToJSON(value.transaction),
    };
}

