/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * OpenAPI spec version: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ShipCargo } from '../models/ShipCargo';
import { ShipCrew } from '../models/ShipCrew';
import { ShipEngine } from '../models/ShipEngine';
import { ShipFrame } from '../models/ShipFrame';
import { ShipFuel } from '../models/ShipFuel';
import { ShipModule } from '../models/ShipModule';
import { ShipMount } from '../models/ShipMount';
import { ShipNav } from '../models/ShipNav';
import { ShipReactor } from '../models/ShipReactor';
import { ShipRegistration } from '../models/ShipRegistration';
import { HttpFile } from '../http/http';

/**
* A ship
*/
export class Ship {
    /**
    * The globally unique identifier of the ship in the following format: `[AGENT_SYMBOL]_[HEX_ID]`
    */
    'symbol': string;
    'registration': ShipRegistration;
    'nav': ShipNav;
    'crew': ShipCrew;
    'frame': ShipFrame;
    'reactor': ShipReactor;
    'engine': ShipEngine;
    'modules': Array<ShipModule>;
    'mounts': Array<ShipMount>;
    'cargo': ShipCargo;
    'fuel': ShipFuel;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "symbol",
            "baseName": "symbol",
            "type": "string",
            "format": ""
        },
        {
            "name": "registration",
            "baseName": "registration",
            "type": "ShipRegistration",
            "format": ""
        },
        {
            "name": "nav",
            "baseName": "nav",
            "type": "ShipNav",
            "format": ""
        },
        {
            "name": "crew",
            "baseName": "crew",
            "type": "ShipCrew",
            "format": ""
        },
        {
            "name": "frame",
            "baseName": "frame",
            "type": "ShipFrame",
            "format": ""
        },
        {
            "name": "reactor",
            "baseName": "reactor",
            "type": "ShipReactor",
            "format": ""
        },
        {
            "name": "engine",
            "baseName": "engine",
            "type": "ShipEngine",
            "format": ""
        },
        {
            "name": "modules",
            "baseName": "modules",
            "type": "Array<ShipModule>",
            "format": ""
        },
        {
            "name": "mounts",
            "baseName": "mounts",
            "type": "Array<ShipMount>",
            "format": ""
        },
        {
            "name": "cargo",
            "baseName": "cargo",
            "type": "ShipCargo",
            "format": ""
        },
        {
            "name": "fuel",
            "baseName": "fuel",
            "type": "ShipFuel",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Ship.attributeTypeMap;
    }

    public constructor() {
    }
}

