/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * OpenAPI spec version: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ShipyardShip } from '../models/ShipyardShip';
import { ShipyardShipTypesInner } from '../models/ShipyardShipTypesInner';
import { ShipyardTransaction } from '../models/ShipyardTransaction';
import { HttpFile } from '../http/http';

/**
* 
*/
export class Shipyard {
    /**
    * The symbol of the shipyard. The symbol is the same as the waypoint where the shipyard is located.
    */
    'symbol': string;
    /**
    * The list of ship types available for purchase at this shipyard.
    */
    'shipTypes': Array<ShipyardShipTypesInner>;
    /**
    * The list of recent transactions at this shipyard.
    */
    'transactions'?: Array<ShipyardTransaction>;
    /**
    * The ships that are currently available for purchase at the shipyard.
    */
    'ships'?: Array<ShipyardShip>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "symbol",
            "baseName": "symbol",
            "type": "string",
            "format": ""
        },
        {
            "name": "shipTypes",
            "baseName": "shipTypes",
            "type": "Array<ShipyardShipTypesInner>",
            "format": ""
        },
        {
            "name": "transactions",
            "baseName": "transactions",
            "type": "Array<ShipyardTransaction>",
            "format": ""
        },
        {
            "name": "ships",
            "baseName": "ships",
            "type": "Array<ShipyardShip>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Shipyard.attributeTypeMap;
    }

    public constructor() {
    }
}

