/* tslint:disable */
/* eslint-disable */
/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Result of a transaction for a ship modification, such as installing a mount or a module.
 * @export
 * @interface ShipModificationTransaction
 */
export interface ShipModificationTransaction {
    /**
     * The symbol of the waypoint where the transaction took place.
     * @type {string}
     * @memberof ShipModificationTransaction
     */
    waypointSymbol: string;
    /**
     * The symbol of the ship that made the transaction.
     * @type {string}
     * @memberof ShipModificationTransaction
     */
    shipSymbol: string;
    /**
     * The symbol of the trade good.
     * @type {string}
     * @memberof ShipModificationTransaction
     */
    tradeSymbol: string;
    /**
     * The total price of the transaction.
     * @type {number}
     * @memberof ShipModificationTransaction
     */
    totalPrice: number;
    /**
     * The timestamp of the transaction.
     * @type {string}
     * @memberof ShipModificationTransaction
     */
    timestamp: string;
}

/**
 * Check if a given object implements the ShipModificationTransaction interface.
 */
export function instanceOfShipModificationTransaction(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "waypointSymbol" in value;
    isInstance = isInstance && "shipSymbol" in value;
    isInstance = isInstance && "tradeSymbol" in value;
    isInstance = isInstance && "totalPrice" in value;
    isInstance = isInstance && "timestamp" in value;

    return isInstance;
}

export function ShipModificationTransactionFromJSON(json: any): ShipModificationTransaction {
    return ShipModificationTransactionFromJSONTyped(json, false);
}

export function ShipModificationTransactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShipModificationTransaction {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'waypointSymbol': json['waypointSymbol'],
        'shipSymbol': json['shipSymbol'],
        'tradeSymbol': json['tradeSymbol'],
        'totalPrice': json['totalPrice'],
        'timestamp': json['timestamp'],
    };
}

export function ShipModificationTransactionToJSON(value?: ShipModificationTransaction | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'waypointSymbol': value.waypointSymbol,
        'shipSymbol': value.shipSymbol,
        'tradeSymbol': value.tradeSymbol,
        'totalPrice': value.totalPrice,
        'timestamp': value.timestamp,
    };
}

