/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * OpenAPI spec version: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ShipNavFlightMode } from '../models/ShipNavFlightMode';
import { ShipNavRoute } from '../models/ShipNavRoute';
import { ShipNavStatus } from '../models/ShipNavStatus';
import { HttpFile } from '../http/http';

/**
* The navigation information of the ship.
*/
export class ShipNav {
    /**
    * The system symbol of the ship\'s current location.
    */
    'systemSymbol': string;
    /**
    * The waypoint symbol of the ship\'s current location, or if the ship is in-transit, the waypoint symbol of the ship\'s destination.
    */
    'waypointSymbol': string;
    'route': ShipNavRoute;
    'status': ShipNavStatus;
    'flightMode': ShipNavFlightMode;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "systemSymbol",
            "baseName": "systemSymbol",
            "type": "string",
            "format": ""
        },
        {
            "name": "waypointSymbol",
            "baseName": "waypointSymbol",
            "type": "string",
            "format": ""
        },
        {
            "name": "route",
            "baseName": "route",
            "type": "ShipNavRoute",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "ShipNavStatus",
            "format": ""
        },
        {
            "name": "flightMode",
            "baseName": "flightMode",
            "type": "ShipNavFlightMode",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ShipNav.attributeTypeMap;
    }

    public constructor() {
    }
}



