/* tslint:disable */
/* eslint-disable */
/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Register201ResponseDataShipFuel } from './Register201ResponseDataShipFuel';
import {
    Register201ResponseDataShipFuelFromJSON,
    Register201ResponseDataShipFuelFromJSONTyped,
    Register201ResponseDataShipFuelToJSON,
} from './Register201ResponseDataShipFuel';
import type { Register201ResponseDataShipNav } from './Register201ResponseDataShipNav';
import {
    Register201ResponseDataShipNavFromJSON,
    Register201ResponseDataShipNavFromJSONTyped,
    Register201ResponseDataShipNavToJSON,
} from './Register201ResponseDataShipNav';

/**
 * 
 * @export
 * @interface WarpShip200ResponseData
 */
export interface WarpShip200ResponseData {
    /**
     * 
     * @type {Register201ResponseDataShipFuel}
     * @memberof WarpShip200ResponseData
     */
    fuel: Register201ResponseDataShipFuel;
    /**
     * 
     * @type {Register201ResponseDataShipNav}
     * @memberof WarpShip200ResponseData
     */
    nav: Register201ResponseDataShipNav;
}

/**
 * Check if a given object implements the WarpShip200ResponseData interface.
 */
export function instanceOfWarpShip200ResponseData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "fuel" in value;
    isInstance = isInstance && "nav" in value;

    return isInstance;
}

export function WarpShip200ResponseDataFromJSON(json: any): WarpShip200ResponseData {
    return WarpShip200ResponseDataFromJSONTyped(json, false);
}

export function WarpShip200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): WarpShip200ResponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fuel': Register201ResponseDataShipFuelFromJSON(json['fuel']),
        'nav': Register201ResponseDataShipNavFromJSON(json['nav']),
    };
}

export function WarpShip200ResponseDataToJSON(value?: WarpShip200ResponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'fuel': Register201ResponseDataShipFuelToJSON(value.fuel),
        'nav': Register201ResponseDataShipNavToJSON(value.nav),
    };
}

